# Generated by Django 5.2.1 on 2025-05-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('medium', models.CharField(choices=[('oil', 'Oil Paint'), ('acrylic', 'Acrylic Paint'), ('watercolor', 'Watercolor'), ('gouache', 'Gouache'), ('pastels', 'Pastels'), ('ink', 'Ink'), ('graphite', 'Graphite/Charcoal'), ('color_pencils', 'Colored Pencils'), ('mixed_media', 'Mixed Media')], default='oil', max_length=100)),
                ('movement', models.CharField(choices=[('abstract', 'Abstract Expressionism'), ('art_deco', 'Art Deco'), ('art_nouveau', 'Art Nouveau'), ('baroque', 'Baroque'), ('classicism', 'Classicism'), ('contemporary', 'Contemporary Art'), ('cubism', 'Cubism'), ('expressionism', 'Expressionism'), ('realism', 'Hyperrealism'), ('impressionism', 'Impressionism'), ('modern', 'Modern Art'), ('neoclassicism', 'Neoclassicism'), ('pop', 'Pop Art'), ('rococo', 'Rococo'), ('surrealism', 'Surrealism')], max_length=100)),
                ('imgae', models.URLField()),
            ],
        ),
    ]
