# Generated by Django 5.2.1 on 2025-05-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='imgae',
            new_name='image',
        ),
    ]
