# Generated by Django 5.2.1 on 2025-05-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_imgae_art_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='medium',
            field=models.CharField(choices=[('oil', 'Oil Paint'), ('acrylic', 'Acrylic Paint'), ('watercolor', 'Watercolor'), ('gouache', 'Gouache'), ('pastels', 'Pastels'), ('ink', 'Ink'), ('graphite', 'Graphite/Charcoal'), ('color_pencils', 'Colored Pencils'), ('mixed_media', 'Mixed Media'), ('sculpture', 'Sculpture'), ('architecture', 'Architecture')], max_length=100),
        ),
    ]
