# Generated by Django 5.2.1 on 2025-05-28 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_art_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.CharField(max_length=50, verbose_name='Year Completed'),
        ),
        migrations.AlterField(
            model_name='art',
            name='medium',
            field=models.CharField(choices=[('oil', 'Oil Paint'), ('acrylic', 'Acrylic Paint'), ('watercolor', 'Watercolor'), ('gouache', 'Gouache'), ('pastels', 'Pastels'), ('ink', 'Ink'), ('graphite', 'Graphite/Charcoal'), ('color_pencils', 'Colored Pencils'), ('mixed_media', 'Mixed Media')], max_length=100),
        ),
        migrations.AlterField(
            model_name='art',
            name='movement',
            field=models.CharField(choices=[('abstract', 'Abstract Expressionism'), ('art_deco', 'Art Deco'), ('art_nouveau', 'Art Nouveau'), ('baroque', 'Baroque'), ('classicism', 'Classicism'), ('contemporary', 'Contemporary Art'), ('cubism', 'Cubism'), ('expressionism', 'Expressionism'), ('realism', 'Hyperrealism'), ('renaissance', 'Renaissance'), ('impressionism', 'Impressionism'), ('modern', 'Modern Art'), ('neoclassicism', 'Neoclassicism'), ('pop', 'Pop Art'), ('rococo', 'Rococo'), ('surrealism', 'Surrealism')], max_length=100),
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('museum', models.CharField(max_length=200)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.art')),
            ],
        ),
    ]
