# Generated by Django 5.2.1 on 2025-05-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_art_date_alter_art_medium_alter_art_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='location',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='art',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Viewed in Person'),
        ),
    ]
