# Generated by Django 5.2.1 on 2025-05-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_art_location_art_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('artist', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=250)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.art')),
            ],
        ),
        migrations.DeleteModel(
            name='Viewing',
        ),
    ]
