# Generated by Django 5.2.1 on 2025-05-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_copy_delete_viewing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='art',
            new_name='artwork',
        ),
    ]
