# Generated by Django 5.2.1 on 2025-05-29 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_art_copy_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Painted'),
            preserve_default=False,
        ),
    ]
