# Generated by Django 5.2.1 on 2025-05-29 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_copy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Painted'),
        ),
    ]
