# Generated by Django 5.2.1 on 2025-05-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_copy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='date',
            field=models.DateField(verbose_name='Date Painted'),
        ),
    ]
