# Generated by Django 5.2.1 on 2025-05-31 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_copy_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='artwork',
            new_name='art',
        ),
    ]
