# Generated by Django 5.2.1 on 2025-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_rename_artwork_copy_art'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copy',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='copy',
            name='notes',
            field=models.CharField(max_length=150),
        ),
    ]
