# Generated by Django 5.2.1 on 2025-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_copy_options_alter_copy_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('aliceBlue', 'Alice Blue'), ('aquamarine', 'Aquamarine'), ('chartreuse', 'Chartreuse'), ('coral', 'Coral'), ('crimson', 'Crimson'), ('seaGree', 'Dark Sea Green'), ('deepPink', 'Deep Pink'), ('dodgerBlue', 'Dodger Blue'), ('slateGray', 'Slate Gray'), ('tomato', 'Tomato')], max_length=20)),
                ('notes', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='art',
            name='medium',
            field=models.CharField(choices=[('oil', 'Oil Paint'), ('acrylic', 'Acrylic Paint'), ('watercolor', 'Watercolor'), ('gouache', 'Gouache'), ('pastels', 'Pastels'), ('ink', 'Ink'), ('graphite', 'Graphite/Charcoal'), ('color_pencils', 'Colored Pencils'), ('mixed_media', 'Mixed Media'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='art',
            name='movement',
            field=models.CharField(blank=True, choices=[('abstract', 'Abstract Expressionism'), ('art_deco', 'Art Deco'), ('art_nouveau', 'Art Nouveau'), ('baroque', 'Baroque'), ('classicism', 'Classicism'), ('contemporary', 'Contemporary Art'), ('cubism', 'Cubism'), ('expressionism', 'Expressionism'), ('realism', 'Hyperrealism'), ('renaissance', 'Renaissance'), ('impressionism', 'Impressionism'), ('modern', 'Modern Art'), ('neoclassicism', 'Neoclassicism'), ('pop', 'Pop Art'), ('rococo', 'Rococo'), ('surrealism', 'Surrealism')], max_length=100, null=True),
        ),
    ]
