# Generated by Django 5.2.1 on 2025-06-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_list_alter_art_medium_alter_art_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='lists',
            field=models.ManyToManyField(to='my_app.list'),
        ),
    ]
